steps:
  - name: 'maven@sha256:c08c6b7a43316bac7c18aa562c6deea93e493eb17750685d19bca80837359dbd'
    id: compile
    entrypoint: mvn
    args:
      - 'compile'
      - 'jib:build'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'kube/' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=moxo-gke'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
        'set',
        'image',
        'deployment',
        'moxo',
        'app=gcr.io/$PROJECT_ID/moxo:latest'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=moxo-gke'