apiVersion: apps/v1
kind: Deployment
metadata:
  name: moxo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moxo
  template:
    metadata:
      labels:
        app: moxo
    spec:
      containers:
        - name: app
          image: gcr.io/bikerapp-e3150/moxo:latest
          ports:
            - containerPort: 8080
          env:
            - name: mongo_host
              value: mongo
            - name: mongo_port
              value: 27017
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: moxo
spec:
  selector:
    app: moxo
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer